/**
 * Tests for ZKP Identity Proofs (Phase 4.1/4.3)
 *
 * Covers:
 *  - ProofOfKeyOwnership generation and verification
 *  - Tamper detection (modified DID, timestamp, nonce, signature)
 *  - Expiry enforcement
 *  - VerifiableCredential issuance and verification
 *  - Selective disclosure via CredentialPresentation
 *  - Performance benchmarks (<100ms generation, <50ms verification)
 */

import { describe, it, expect, beforeAll } from 'vitest'
import { keys } from '@libp2p/crypto'
import type { PrivateKey } from '@libp2p/interface'
import {
  generateOwnershipProof,
  verifyOwnershipProof,
  issueCredential,
  verifyCredential,
  createPresentation,
  verifyPresentation,
  issueCapabilityCredential,
  type ProofOfKeyOwnership,
  type VerifiableCredential,
} from '../src/zkp.js'
import { deriveDidKey } from '../src/identity.js'

// ── Test fixtures ─────────────────────────────────────────────────────────────

let aliceKey: PrivateKey
let aliceDid: string
let bobKey: PrivateKey
let bobDid: string

beforeAll(async () => {
  aliceKey = await keys.generateKeyPair('Ed25519')
  aliceDid = deriveDidKey(aliceKey.publicKey)

  bobKey = await keys.generateKeyPair('Ed25519')
  bobDid = deriveDidKey(bobKey.publicKey)
})

// ── ProofOfKeyOwnership ───────────────────────────────────────────────────────

describe('ProofOfKeyOwnership', () => {
  describe('generation', () => {
    it('generates a proof with required fields', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey)

      expect(proof.type).toBe('ProofOfKeyOwnership')
      expect(proof.did).toBe(aliceDid)
      expect(proof.issuedAt).toMatch(/^\d{4}-\d{2}-\d{2}T/)
      expect(proof.expiresAt).toMatch(/^\d{4}-\d{2}-\d{2}T/)
      expect(proof.nonce).toHaveLength(64) // 32 bytes hex
      expect(proof.challenge).toHaveLength(64) // sha256 hex
      expect(proof.signature).toHaveLength(128) // 64-byte ed25519 sig as hex
    })

    it('sets expiry 5 minutes in the future by default', async () => {
      const before = Date.now()
      const proof = await generateOwnershipProof(aliceDid, aliceKey)
      const after = Date.now()

      const expiryMs = new Date(proof.expiresAt).getTime()
      const issuedMs = new Date(proof.issuedAt).getTime()

      expect(expiryMs - issuedMs).toBeCloseTo(5 * 60 * 1000, -2)
      expect(issuedMs).toBeGreaterThanOrEqual(before)
      expect(issuedMs).toBeLessThanOrEqual(after)
    })

    it('respects custom TTL', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey, { ttlMs: 60_000 })
      const expiryMs = new Date(proof.expiresAt).getTime()
      const issuedMs = new Date(proof.issuedAt).getTime()
      expect(expiryMs - issuedMs).toBeCloseTo(60_000, -2)
    })

    it('includes optional peerId when provided', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey, {
        peerId: '12D3KooWTestPeer',
      })
      expect(proof.peerId).toBe('12D3KooWTestPeer')
    })

    it('includes optional context when provided', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey, {
        context: { purpose: 'capability-negotiation', network: 'test-network' },
      })
      expect(proof.context?.purpose).toBe('capability-negotiation')
      expect(proof.context?.network).toBe('test-network')
    })

    it('generates different nonces for each proof (no replay)', async () => {
      const proof1 = await generateOwnershipProof(aliceDid, aliceKey)
      const proof2 = await generateOwnershipProof(aliceDid, aliceKey)
      expect(proof1.nonce).not.toBe(proof2.nonce)
      expect(proof1.challenge).not.toBe(proof2.challenge)
      expect(proof1.signature).not.toBe(proof2.signature)
    })

    it('completes in under 100ms', async () => {
      const start = Date.now()
      await generateOwnershipProof(aliceDid, aliceKey)
      const elapsed = Date.now() - start
      expect(elapsed).toBeLessThan(100)
    })
  })

  describe('verification', () => {
    it('verifies a valid proof', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey)
      const valid = await verifyOwnershipProof(proof)
      expect(valid).toBe(true)
    })

    it('verifies proof generated by bob', async () => {
      const proof = await generateOwnershipProof(bobDid, bobKey)
      const valid = await verifyOwnershipProof(proof)
      expect(valid).toBe(true)
    })

    it('rejects proof with wrong type', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey)
      const tampered = { ...proof, type: 'EvilProof' as 'ProofOfKeyOwnership' }
      expect(await verifyOwnershipProof(tampered)).toBe(false)
    })

    it('rejects tampered DID', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey)
      const tampered = { ...proof, did: bobDid }
      expect(await verifyOwnershipProof(tampered)).toBe(false)
    })

    it('rejects tampered timestamp', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey)
      const tampered = { ...proof, issuedAt: new Date(Date.now() - 1000).toISOString() }
      expect(await verifyOwnershipProof(tampered)).toBe(false)
    })

    it('rejects tampered nonce', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey)
      const tampered = { ...proof, nonce: 'a'.repeat(64) }
      expect(await verifyOwnershipProof(tampered)).toBe(false)
    })

    it('rejects tampered signature', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey)
      const tampered = { ...proof, signature: 'b'.repeat(128) }
      expect(await verifyOwnershipProof(tampered)).toBe(false)
    })

    it('rejects cross-signer attack (alice signature on bob proof)', async () => {
      const aliceProof = await generateOwnershipProof(aliceDid, aliceKey)
      const bobProof = await generateOwnershipProof(bobDid, bobKey)
      // Use alice's challenge/signature with bob's DID
      const crossProof: ProofOfKeyOwnership = {
        ...bobProof,
        challenge: aliceProof.challenge,
        signature: aliceProof.signature,
        nonce: aliceProof.nonce,
        issuedAt: aliceProof.issuedAt,
        expiresAt: aliceProof.expiresAt,
      }
      expect(await verifyOwnershipProof(crossProof)).toBe(false)
    })

    it('rejects expired proof', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey, { ttlMs: 1 })
      // Wait 5ms to ensure expiry
      await new Promise(r => setTimeout(r, 10))
      expect(await verifyOwnershipProof(proof)).toBe(false)
    })

    it('completes verification in under 50ms', async () => {
      const proof = await generateOwnershipProof(aliceDid, aliceKey)
      const start = Date.now()
      await verifyOwnershipProof(proof)
      const elapsed = Date.now() - start
      expect(elapsed).toBeLessThan(50)
    })
  })
})

// ── VerifiableCredential ──────────────────────────────────────────────────────

describe('VerifiableCredential', () => {
  describe('issuance', () => {
    it('issues a credential with required W3C VC fields', async () => {
      const { credential } = await issueCredential(aliceDid, aliceKey, aliceDid, [
        { type: 'memory.read', value: 'true' },
        { type: 'memory.write', value: 'true' },
      ])

      expect(credential['@context']).toContain('https://www.w3.org/2018/credentials/v1')
      expect(credential.type).toContain('VerifiableCredential')
      expect(credential.type).toContain('SubspaceAgentCredential')
      expect(credential.issuer).toBe(aliceDid)
      expect(credential.credentialSubject.id).toBe(aliceDid)
      expect(credential.credentialSubject.claims).toHaveLength(2)
      expect(credential.proof.type).toBe('Ed25519Signature2020')
      expect(credential.proof.proofValue).toHaveLength(128) // 64-byte sig
    })

    it('returns nonces for selective disclosure', async () => {
      const { nonces } = await issueCredential(aliceDid, aliceKey, aliceDid, [
        { type: 'capability', value: 'memory.read' },
        { type: 'capability', value: 'memory.write' },
      ])

      expect(typeof nonces.capability).toBe('string')
      expect(nonces.capability).toHaveLength(64) // 32 bytes hex
    })

    it('includes commitment hashes in claims', async () => {
      const { credential } = await issueCredential(aliceDid, aliceKey, aliceDid, [
        { type: 'score', value: '42' },
      ])
      const claim = credential.credentialSubject.claims[0]
      expect(claim.commitment).toHaveLength(64) // sha256 hex
      expect(claim.value).toBe('42')
    })

    it('alice can issue a credential for bob (cross-entity)', async () => {
      const { credential } = await issueCredential(aliceDid, aliceKey, bobDid, [
        { type: 'role', value: 'trusted-peer' },
      ])
      expect(credential.issuer).toBe(aliceDid)
      expect(credential.credentialSubject.id).toBe(bobDid)
    })
  })

  describe('verification', () => {
    it('verifies a valid credential', async () => {
      const { credential } = await issueCredential(aliceDid, aliceKey, aliceDid, [
        { type: 'memory.read', value: 'true' },
      ])
      expect(await verifyCredential(credential)).toBe(true)
    })

    it('rejects tampered claim value', async () => {
      const { credential } = await issueCredential(aliceDid, aliceKey, aliceDid, [
        { type: 'score', value: '10' },
      ])
      const tampered: VerifiableCredential = {
        ...credential,
        credentialSubject: {
          ...credential.credentialSubject,
          claims: [{ ...credential.credentialSubject.claims[0], value: '9999' }],
        },
      }
      expect(await verifyCredential(tampered)).toBe(false)
    })

    it('rejects credential with wrong issuer key', async () => {
      const { credential } = await issueCredential(aliceDid, aliceKey, aliceDid, [
        { type: 'membership', value: 'network-1' },
      ])
      // Replace issuer DID with bob's — signature won't match
      const tampered: VerifiableCredential = { ...credential, issuer: bobDid }
      expect(await verifyCredential(tampered)).toBe(false)
    })
  })
})

// ── Selective Disclosure / Presentation ───────────────────────────────────────

describe('CredentialPresentation (selective disclosure)', () => {
  it('creates a valid presentation revealing a subset of claims', async () => {
    const { credential, nonces } = await issueCredential(aliceDid, aliceKey, aliceDid, [
      { type: 'memory.read', value: 'true' },
      { type: 'memory.write', value: 'true' },
      { type: 'secret-claim', value: 'do-not-reveal' },
    ])

    const presentation = await createPresentation(
      credential,
      nonces,
      ['memory.read', 'memory.write'],
      aliceDid,
      aliceKey
    )

    expect(presentation.type).toBe('CredentialPresentation')
    expect(presentation.revealedClaims).toHaveLength(2)
    expect(presentation.hiddenCommitments).toHaveLength(1)
    expect(presentation.revealedClaims[0].claim.type).toBe('memory.read')
    // The secret claim's commitment is present but value is hidden
    expect(presentation.hiddenCommitments[0]).toHaveLength(64)
  })

  it('verifies a valid selective presentation', async () => {
    const { credential, nonces } = await issueCredential(aliceDid, aliceKey, aliceDid, [
      { type: 'role', value: 'admin' },
      { type: 'private-key', value: 'secret-12345' },
    ])

    const presentation = await createPresentation(
      credential,
      nonces,
      ['role'], // reveal only role, hide private-key
      aliceDid,
      aliceKey
    )

    expect(await verifyPresentation(presentation)).toBe(true)
    // Verifier can see the role
    expect(presentation.revealedClaims[0].claim.value).toBe('admin')
    // Verifier cannot see the private-key value
    expect(presentation.hiddenCommitments).toHaveLength(1)
  })

  it('rejects tampered revealed claim', async () => {
    const { credential, nonces } = await issueCredential(aliceDid, aliceKey, aliceDid, [
      { type: 'score', value: '50' },
    ])

    const presentation = await createPresentation(credential, nonces, ['score'], aliceDid, aliceKey)

    // Tamper with the revealed claim value
    const tampered = {
      ...presentation,
      revealedClaims: [
        {
          ...presentation.revealedClaims[0],
          claim: { ...presentation.revealedClaims[0].claim, value: '9999' },
        },
      ],
    }

    expect(await verifyPresentation(tampered)).toBe(false)
  })

  it('rejects tampered nonce in revealed claim', async () => {
    const { credential, nonces } = await issueCredential(aliceDid, aliceKey, aliceDid, [
      { type: 'level', value: 'gold' },
    ])

    const presentation = await createPresentation(credential, nonces, ['level'], aliceDid, aliceKey)

    const tampered = {
      ...presentation,
      revealedClaims: [
        {
          ...presentation.revealedClaims[0],
          nonce: 'f'.repeat(64), // wrong nonce
        },
      ],
    }

    expect(await verifyPresentation(tampered)).toBe(false)
  })

  it('rejects presentation with expired ownership proof', async () => {
    const { credential, nonces } = await issueCredential(aliceDid, aliceKey, aliceDid, [
      { type: 'membership', value: 'network-1' },
    ])

    const presentation = await createPresentation(
      credential,
      nonces,
      ['membership'],
      aliceDid,
      aliceKey
    )

    // Backdating the expiry of the ownership proof
    const tampered = {
      ...presentation,
      ownershipProof: {
        ...presentation.ownershipProof,
        expiresAt: new Date(Date.now() - 1000).toISOString(),
      },
    }

    expect(await verifyPresentation(tampered)).toBe(false)
  })
})

// ── Capability Credential convenience ────────────────────────────────────────

describe('issueCapabilityCredential', () => {
  it('issues a self-signed capability VC', async () => {
    const caps = ['memory.read', 'memory.write', 'negotiate.query']
    const { credential, nonces } = await issueCapabilityCredential(aliceDid, aliceKey, caps)

    expect(credential.issuer).toBe(aliceDid)
    expect(credential.credentialSubject.id).toBe(aliceDid)
    expect(credential.credentialSubject.claims).toHaveLength(3)
    expect(credential.credentialSubject.claims.every(c => c.type === 'capability')).toBe(true)
    expect(Object.keys(nonces)).toHaveLength(1) // all same type = same key
  })

  it('produces a verifiable credential', async () => {
    const { credential } = await issueCapabilityCredential(aliceDid, aliceKey, ['memory.read'])
    expect(await verifyCredential(credential)).toBe(true)
  })

  it('has an expiration 24 hours from issuance', async () => {
    const { credential } = await issueCapabilityCredential(aliceDid, aliceKey, ['memory.read'])
    const issued = new Date(credential.issuanceDate).getTime()
    const expires = new Date(credential.expirationDate!).getTime()
    const ttlHours = (expires - issued) / (1000 * 60 * 60)
    expect(ttlHours).toBeCloseTo(24, 0)
  })
})
